In [ ]:
import numpy as np
a = np.array([1,3,0],float)
print(a>2)

[False  True False]


In [ ]:
b = np.array((2,3,4))
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
a = np.array([[1,3,5],[2,4,6],[9,9,9]])
print(a)

[[1 3 5]
 [2 4 6]
 [9 9 9]]


In [ ]:
arr = np.zeros((3,3),int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
arr = np.ones((3,3),int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
a = np.arange(10,30,5)
print(a)

[10 15 20 25]


In [ ]:
arr = np.linspace(0,2,9)
print(arr)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [ ]:
arr  =  np.identity(3,int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [ ]:
import numpy as mp
x = np.random.randint(1,2,5)
print(x)

[1 1 1 1 1]
